### ISSUE TITLE
Black Image when capture

### ISSUE THREAD

**Issue by kabdelhalem** [dashesy/pyavfcam#7]
I used the original code:
`import pyavfcam

# Open the default video source
cam = pyavfcam.AVFCam(sinks='image')
cam.snap_picture('test.png')

print( "Saved test.jpg (Size: " + str(cam.shape[0]) + " x " + str(cam.shape[1]) + ")")`

all i get is a black image, even if i use test.jpg instead of png

**Comment by dashesy** [comment]
Looks like [this](https://stackoverflow.com/questions/25958021/get-black-photo-when-capture-with-avfoundation) issue, specially if the second capture is not black. Sorry I do not even own a Mac device anymore to fix this.

**Comment by kabdelhalem** [comment]
For anyone else with this issue, the fix is to import the time module
```
import pyavfcam
import time

# Open the default video source
cam = pyavfcam.AVFCam(sinks='image')

time.sleep(1)

cam.snap_picture('test.png')


print( "Saved test.jpg (Size: " + str(cam.shape[0]) + " x " + str(cam.shape[1]) + ")")
```
The problem was that the camera would open and close before a picture was taken, this fixes the issue by letting the camera warm up for one second and then takes a picture.
